# Generated by Django 4.2.5 on 2023-11-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idlocalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='nombre', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_doc', models.CharField(db_column='documento', max_length=5)),
                ('n_doc', models.CharField(db_column='no_documento', max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('urlfoto', models.CharField(blank=True, db_column='url_foto', max_length=2048, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('idlocalidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.localidad')),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('nit', models.CharField(db_column='nit', max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('urlfoto', models.CharField(blank=True, max_length=700, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso')),
                ('publicacionesCount', models.IntegerField(db_column='n_publicaciones', default=0)),
                ('idlocalidad', models.ForeignKey(db_column='idlocalidad', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.localidad')),
            ],
            options={
                'db_table': 'organizaciones',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(db_column='es_admin', default=False)),
                ('is_active', models.BooleanField(db_column='activada', default=True)),
                ('is_staff', models.BooleanField(db_column='es_moderador', default=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='group_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='users_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
