# Generated by Django 4.2.5 on 2023-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='urlfoto',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
