# Generated by Django 4.2.5 on 2023-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizacion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='publicacionesCount',
            field=models.IntegerField(db_column='n_publicaciones', default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='urlfoto',
            field=models.CharField(blank=True, db_column='url_foto', max_length=2048, null=True),
        ),
    ]
