# Generated by Django 4.2.5 on 2023-10-31 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=300)),
                ('es_respuesta', models.BooleanField(default=False)),
                ('comentador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='accounts.persona')),
                ('comentador_org', models.ForeignKey(blank=True, db_column='idComentadorOrg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_organizacion', to='accounts.organizacion')),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='posts.comentario')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.IntegerField(db_column='idpublicacion', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=45)),
                ('titulo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('fechapublicacion', models.DateTimeField(max_length=45)),
                ('likes', models.IntegerField(default=0)),
                ('comentarios', models.ManyToManyField(related_name='publicaciones_comentarios', to='posts.comentario')),
                ('idorganizacion', models.ForeignKey(blank=True, db_column='idorganizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicaciones_organizacion', to='accounts.organizacion')),
                ('idpersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicaciones_integrante_organizacion', to='accounts.persona')),
            ],
            options={
                'db_table': 'publicaciones',
            },
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicaciones',
            field=models.ManyToManyField(related_name='comentarios_publicaciones', to='posts.publicacion'),
        ),
    ]
