# Generated by Django 4.2.5 on 2023-09-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechapublicacion',
            field=models.DateTimeField(max_length=45),
        ),
    ]
