# Generated by Django 4.2.5 on 2023-09-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0002_alter_publicacion_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='accounts.persona'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='respondedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_respuesta', to='accounts.persona'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='idpersona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Publicaciones_integrante_organizacion', to='accounts.persona'),
        ),
    ]
