# Generated by Django 4.2.5 on 2023-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_publicacion_idpublicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
