# Generated by Django 4.2.5 on 2023-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_mascota_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='urlfoto',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
