# Generated by Django 4.2.5 on 2023-09-29 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('especie', models.IntegerField()),
                ('raza', models.CharField(max_length=45)),
                ('sexo', models.IntegerField()),
                ('fechanacimiento', models.DateField()),
                ('urlfoto', models.CharField(blank=True, max_length=700, null=True)),
                ('adoptada', models.BooleanField(default=False)),
                ('idorganizacion', models.ForeignKey(blank=True, db_column='id_organizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.organizacion')),
                ('idpersona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.persona')),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
    ]
