# Generated by Django 4.2.5 on 2023-09-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('race', models.TextField(max_length=20)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
