# Generated by Django 4.2.5 on 2023-10-30 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizacion_name'),
        ('posts', '0003_alter_comentario_comentador_and_more'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='publicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascota', to='posts.publicacion'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='idorganizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_organizacion', to='accounts.organizacion'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='idpersona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_persona', to='accounts.persona'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(max_length=45),
        ),
    ]
