# Generated by Django 4.2.5 on 2023-10-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='name',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50),
        ),
    ]
