# Generated by Django 4.2.5 on 2023-09-30 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idpublicacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=45)),
                ('titulo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('fechapublicacion', models.CharField(max_length=45)),
                ('idorganizacion', models.ForeignKey(blank=True, db_column='idorganizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Publicaciones_organizacion', to='accounts.organizacion')),
                ('idpersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Publicaciones_integrante_organizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=300)),
                ('respuesta', models.CharField(blank=True, max_length=300, null=True)),
                ('comentador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('comentador_org', models.ForeignKey(blank=True, db_column='idComentadorOrg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_organizacion', to='accounts.organizacion')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.publicacion')),
                ('respondedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_respuesta', to=settings.AUTH_USER_MODEL)),
                ('respondedor_org', models.ForeignKey(blank=True, db_column='idRespondedorOrg', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_respuesta_organizacion', to='accounts.organizacion')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
    ]
