# Generated by Django 4.2.5 on 2023-10-30 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizacion_name'),
        ('posts', '0003_alter_comentario_comentador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='idpublicacion',
            field=models.IntegerField(db_column='idpublicacion', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='idpublicacion',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='respondedor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='respondedor_org',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='posts.comentario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='es_respuesta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicaciones',
            field=models.ManyToManyField(related_name='comentarios_publicaciones', to='posts.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='comentarios',
            field=models.ManyToManyField(related_name='publicaciones_comentarios', to='posts.comentario'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='idorganizacion',
            field=models.ForeignKey(blank=True, db_column='idorganizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicaciones_organizacion', to='accounts.organizacion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='idpersona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicaciones_integrante_organizacion', to='accounts.persona'),
        ),
    ]
