# Generated by Django 4.2.5 on 2023-11-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_comentario_autor_organizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=2048),
        ),
    ]
