# Generated by Django 4.2.5 on 2023-11-01 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizacion_publicacionescount_and_more'),
        ('posts', '0005_publicacion_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentador',
            new_name='autor_persona',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentador_org',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='es_respuesta',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='publicaciones',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='idpersona',
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor_organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='accounts.organizacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fechapublicacion',
            field=models.DateTimeField(db_column='fecha_publicacion', default=datetime.datetime(2023, 11, 1, 16, 25, 50, 928818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posts.publicacion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechapublicacion',
            field=models.DateTimeField(db_column='fecha_publicacion', default=datetime.datetime(2023, 11, 1, 16, 25, 50, 927816, tzinfo=datetime.timezone.utc)),
        ),
    ]
