# Generated by Django 4.2.5 on 2023-11-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_comentador_comentario_autor_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechapublicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechapublicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
