# Generated by Django 4.2.5 on 2023-11-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comentario_fechapublicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='n_mascotas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='n_mascotas_adoptadas',
            field=models.IntegerField(default=0),
        ),
    ]
